/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdministrationRouteImport } from './routes/_authenticated/administration'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEstimatesRouteImport } from './routes/_authenticated/estimates'
import { Route as AuthenticatedFacilitiesRouteImport } from './routes/_authenticated/facilities'
import { Route as AuthenticatedFindingsRouteImport } from './routes/_authenticated/findings'
import { Route as AuthenticatedIntakeRouteImport } from './routes/_authenticated/intake'
import { Route as AuthenticatedOrganizationsRouteImport } from './routes/_authenticated/organizations'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedAssessmentsIndexRouteImport } from './routes/_authenticated/assessments/index'
import { Route as AuthenticatedAssessmentsAssessmentIdRouteImport } from './routes/_authenticated/assessments/$assessmentId'
import { Route as AuthenticatedAssessmentsNewRouteImport } from './routes/_authenticated/assessments/new'
import { Route as AuthenticatedCapabilityIndexRouteImport } from './routes/_authenticated/capability/index'
import { Route as AuthenticatedCapabilityAssessmentIdRouteImport } from './routes/_authenticated/capability/$assessmentId'
import { Route as AuthenticatedFieldIndexRouteImport } from './routes/_authenticated/field/index'
import { Route as AuthenticatedFieldFieldIdRouteImport } from './routes/_authenticated/field/$fieldId'
import { Route as AuthenticatedProductionIndexRouteImport } from './routes/_authenticated/production.index'
import { Route as AuthenticatedProductionLibrariesRouteImport } from './routes/_authenticated/production.libraries'
import { Route as AuthenticatedProductionNewRouteImport } from './routes/_authenticated/production.new'
import { Route as AuthenticatedProductionJobsJobIdRouteImport } from './routes/_authenticated/production.jobs.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdministrationRoute =
  AuthenticatedAdministrationRouteImport.update({
    id: '/administration',
    path: '/administration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstimatesRoute = AuthenticatedEstimatesRouteImport.update({
  id: '/estimates',
  path: '/estimates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFacilitiesRoute = AuthenticatedFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFindingsRoute = AuthenticatedFindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntakeRoute = AuthenticatedIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrganizationsRoute =
  AuthenticatedOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessmentsIndexRoute =
  AuthenticatedAssessmentsIndexRouteImport.update({
    id: '/assessments/',
    path: '/assessments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentsAssessmentIdRoute =
  AuthenticatedAssessmentsAssessmentIdRouteImport.update({
    id: '/assessments/$assessmentId',
    path: '/assessments/$assessmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentsNewRoute =
  AuthenticatedAssessmentsNewRouteImport.update({
    id: '/assessments/new',
    path: '/assessments/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCapabilityIndexRoute =
  AuthenticatedCapabilityIndexRouteImport.update({
    id: '/capability/',
    path: '/capability/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCapabilityAssessmentIdRoute =
  AuthenticatedCapabilityAssessmentIdRouteImport.update({
    id: '/capability/$assessmentId',
    path: '/capability/$assessmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFieldIndexRoute = AuthenticatedFieldIndexRouteImport.update({
  id: '/field/',
  path: '/field/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFieldFieldIdRoute =
  AuthenticatedFieldFieldIdRouteImport.update({
    id: '/field/$fieldId',
    path: '/field/$fieldId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionIndexRoute =
  AuthenticatedProductionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const AuthenticatedProductionLibrariesRoute =
  AuthenticatedProductionLibrariesRouteImport.update({
    id: '/libraries',
    path: '/libraries',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const AuthenticatedProductionNewRoute =
  AuthenticatedProductionNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const AuthenticatedProductionJobsJobIdRoute =
  AuthenticatedProductionJobsJobIdRouteImport.update({
    id: '/jobs/$jobId',
    path: '/jobs/$jobId',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/administration': typeof AuthenticatedAdministrationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estimates': typeof AuthenticatedEstimatesRoute
  '/facilities': typeof AuthenticatedFacilitiesRoute
  '/findings': typeof AuthenticatedFindingsRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/organizations': typeof AuthenticatedOrganizationsRoute
  '/production': typeof AuthenticatedProductionRouteWithChildren
  '/projects': typeof AuthenticatedProjectsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/assessments/$assessmentId': typeof AuthenticatedAssessmentsAssessmentIdRoute
  '/assessments/new': typeof AuthenticatedAssessmentsNewRoute
  '/capability/$assessmentId': typeof AuthenticatedCapabilityAssessmentIdRoute
  '/field/$fieldId': typeof AuthenticatedFieldFieldIdRoute
  '/production/libraries': typeof AuthenticatedProductionLibrariesRoute
  '/production/new': typeof AuthenticatedProductionNewRoute
  '/assessments/': typeof AuthenticatedAssessmentsIndexRoute
  '/capability/': typeof AuthenticatedCapabilityIndexRoute
  '/field/': typeof AuthenticatedFieldIndexRoute
  '/production/': typeof AuthenticatedProductionIndexRoute
  '/production/jobs/$jobId': typeof AuthenticatedProductionJobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/administration': typeof AuthenticatedAdministrationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estimates': typeof AuthenticatedEstimatesRoute
  '/facilities': typeof AuthenticatedFacilitiesRoute
  '/findings': typeof AuthenticatedFindingsRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/organizations': typeof AuthenticatedOrganizationsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/assessments/$assessmentId': typeof AuthenticatedAssessmentsAssessmentIdRoute
  '/assessments/new': typeof AuthenticatedAssessmentsNewRoute
  '/capability/$assessmentId': typeof AuthenticatedCapabilityAssessmentIdRoute
  '/field/$fieldId': typeof AuthenticatedFieldFieldIdRoute
  '/production/libraries': typeof AuthenticatedProductionLibrariesRoute
  '/production/new': typeof AuthenticatedProductionNewRoute
  '/assessments': typeof AuthenticatedAssessmentsIndexRoute
  '/capability': typeof AuthenticatedCapabilityIndexRoute
  '/field': typeof AuthenticatedFieldIndexRoute
  '/production': typeof AuthenticatedProductionIndexRoute
  '/production/jobs/$jobId': typeof AuthenticatedProductionJobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/administration': typeof AuthenticatedAdministrationRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/estimates': typeof AuthenticatedEstimatesRoute
  '/_authenticated/facilities': typeof AuthenticatedFacilitiesRoute
  '/_authenticated/findings': typeof AuthenticatedFindingsRoute
  '/_authenticated/intake': typeof AuthenticatedIntakeRoute
  '/_authenticated/organizations': typeof AuthenticatedOrganizationsRoute
  '/_authenticated/production': typeof AuthenticatedProductionRouteWithChildren
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/assessments/$assessmentId': typeof AuthenticatedAssessmentsAssessmentIdRoute
  '/_authenticated/assessments/new': typeof AuthenticatedAssessmentsNewRoute
  '/_authenticated/capability/$assessmentId': typeof AuthenticatedCapabilityAssessmentIdRoute
  '/_authenticated/field/$fieldId': typeof AuthenticatedFieldFieldIdRoute
  '/_authenticated/production/libraries': typeof AuthenticatedProductionLibrariesRoute
  '/_authenticated/production/new': typeof AuthenticatedProductionNewRoute
  '/_authenticated/assessments/': typeof AuthenticatedAssessmentsIndexRoute
  '/_authenticated/capability/': typeof AuthenticatedCapabilityIndexRoute
  '/_authenticated/field/': typeof AuthenticatedFieldIndexRoute
  '/_authenticated/production/': typeof AuthenticatedProductionIndexRoute
  '/_authenticated/production/jobs/$jobId': typeof AuthenticatedProductionJobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/administration'
    | '/dashboard'
    | '/estimates'
    | '/facilities'
    | '/findings'
    | '/intake'
    | '/organizations'
    | '/production'
    | '/projects'
    | '/reports'
    | '/templates'
    | '/assessments/$assessmentId'
    | '/assessments/new'
    | '/capability/$assessmentId'
    | '/field/$fieldId'
    | '/production/libraries'
    | '/production/new'
    | '/assessments/'
    | '/capability/'
    | '/field/'
    | '/production/'
    | '/production/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/administration'
    | '/dashboard'
    | '/estimates'
    | '/facilities'
    | '/findings'
    | '/intake'
    | '/organizations'
    | '/projects'
    | '/reports'
    | '/templates'
    | '/assessments/$assessmentId'
    | '/assessments/new'
    | '/capability/$assessmentId'
    | '/field/$fieldId'
    | '/production/libraries'
    | '/production/new'
    | '/assessments'
    | '/capability'
    | '/field'
    | '/production'
    | '/production/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/administration'
    | '/_authenticated/dashboard'
    | '/_authenticated/estimates'
    | '/_authenticated/facilities'
    | '/_authenticated/findings'
    | '/_authenticated/intake'
    | '/_authenticated/organizations'
    | '/_authenticated/production'
    | '/_authenticated/projects'
    | '/_authenticated/reports'
    | '/_authenticated/templates'
    | '/_authenticated/assessments/$assessmentId'
    | '/_authenticated/assessments/new'
    | '/_authenticated/capability/$assessmentId'
    | '/_authenticated/field/$fieldId'
    | '/_authenticated/production/libraries'
    | '/_authenticated/production/new'
    | '/_authenticated/assessments/'
    | '/_authenticated/capability/'
    | '/_authenticated/field/'
    | '/_authenticated/production/'
    | '/_authenticated/production/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/administration': {
      id: '/_authenticated/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AuthenticatedAdministrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estimates': {
      id: '/_authenticated/estimates'
      path: '/estimates'
      fullPath: '/estimates'
      preLoaderRoute: typeof AuthenticatedEstimatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facilities': {
      id: '/_authenticated/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof AuthenticatedFacilitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/findings': {
      id: '/_authenticated/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof AuthenticatedFindingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intake': {
      id: '/_authenticated/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof AuthenticatedIntakeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations': {
      id: '/_authenticated/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthenticatedOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/': {
      id: '/_authenticated/assessments/'
      path: '/assessments'
      fullPath: '/assessments/'
      preLoaderRoute: typeof AuthenticatedAssessmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/$assessmentId': {
      id: '/_authenticated/assessments/$assessmentId'
      path: '/assessments/$assessmentId'
      fullPath: '/assessments/$assessmentId'
      preLoaderRoute: typeof AuthenticatedAssessmentsAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/new': {
      id: '/_authenticated/assessments/new'
      path: '/assessments/new'
      fullPath: '/assessments/new'
      preLoaderRoute: typeof AuthenticatedAssessmentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/capability/': {
      id: '/_authenticated/capability/'
      path: '/capability'
      fullPath: '/capability/'
      preLoaderRoute: typeof AuthenticatedCapabilityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/capability/$assessmentId': {
      id: '/_authenticated/capability/$assessmentId'
      path: '/capability/$assessmentId'
      fullPath: '/capability/$assessmentId'
      preLoaderRoute: typeof AuthenticatedCapabilityAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/field/': {
      id: '/_authenticated/field/'
      path: '/field'
      fullPath: '/field/'
      preLoaderRoute: typeof AuthenticatedFieldIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/field/$fieldId': {
      id: '/_authenticated/field/$fieldId'
      path: '/field/$fieldId'
      fullPath: '/field/$fieldId'
      preLoaderRoute: typeof AuthenticatedFieldFieldIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production/': {
      id: '/_authenticated/production/'
      path: '/'
      fullPath: '/production/'
      preLoaderRoute: typeof AuthenticatedProductionIndexRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/_authenticated/production/libraries': {
      id: '/_authenticated/production/libraries'
      path: '/libraries'
      fullPath: '/production/libraries'
      preLoaderRoute: typeof AuthenticatedProductionLibrariesRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/_authenticated/production/new': {
      id: '/_authenticated/production/new'
      path: '/new'
      fullPath: '/production/new'
      preLoaderRoute: typeof AuthenticatedProductionNewRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/_authenticated/production/jobs/$jobId': {
      id: '/_authenticated/production/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/production/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedProductionJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
  }
}

interface AuthenticatedProductionRouteChildren {
  AuthenticatedProductionLibrariesRoute: typeof AuthenticatedProductionLibrariesRoute
  AuthenticatedProductionNewRoute: typeof AuthenticatedProductionNewRoute
  AuthenticatedProductionIndexRoute: typeof AuthenticatedProductionIndexRoute
  AuthenticatedProductionJobsJobIdRoute: typeof AuthenticatedProductionJobsJobIdRoute
}

const AuthenticatedProductionRouteChildren: AuthenticatedProductionRouteChildren =
  {
    AuthenticatedProductionLibrariesRoute:
      AuthenticatedProductionLibrariesRoute,
    AuthenticatedProductionNewRoute: AuthenticatedProductionNewRoute,
    AuthenticatedProductionIndexRoute: AuthenticatedProductionIndexRoute,
    AuthenticatedProductionJobsJobIdRoute:
      AuthenticatedProductionJobsJobIdRoute,
  }

const AuthenticatedProductionRouteWithChildren =
  AuthenticatedProductionRoute._addFileChildren(
    AuthenticatedProductionRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdministrationRoute: typeof AuthenticatedAdministrationRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEstimatesRoute: typeof AuthenticatedEstimatesRoute
  AuthenticatedFacilitiesRoute: typeof AuthenticatedFacilitiesRoute
  AuthenticatedFindingsRoute: typeof AuthenticatedFindingsRoute
  AuthenticatedIntakeRoute: typeof AuthenticatedIntakeRoute
  AuthenticatedOrganizationsRoute: typeof AuthenticatedOrganizationsRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRouteWithChildren
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedAssessmentsAssessmentIdRoute: typeof AuthenticatedAssessmentsAssessmentIdRoute
  AuthenticatedAssessmentsNewRoute: typeof AuthenticatedAssessmentsNewRoute
  AuthenticatedCapabilityAssessmentIdRoute: typeof AuthenticatedCapabilityAssessmentIdRoute
  AuthenticatedFieldFieldIdRoute: typeof AuthenticatedFieldFieldIdRoute
  AuthenticatedAssessmentsIndexRoute: typeof AuthenticatedAssessmentsIndexRoute
  AuthenticatedCapabilityIndexRoute: typeof AuthenticatedCapabilityIndexRoute
  AuthenticatedFieldIndexRoute: typeof AuthenticatedFieldIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdministrationRoute: AuthenticatedAdministrationRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEstimatesRoute: AuthenticatedEstimatesRoute,
  AuthenticatedFacilitiesRoute: AuthenticatedFacilitiesRoute,
  AuthenticatedFindingsRoute: AuthenticatedFindingsRoute,
  AuthenticatedIntakeRoute: AuthenticatedIntakeRoute,
  AuthenticatedOrganizationsRoute: AuthenticatedOrganizationsRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRouteWithChildren,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedAssessmentsAssessmentIdRoute:
    AuthenticatedAssessmentsAssessmentIdRoute,
  AuthenticatedAssessmentsNewRoute: AuthenticatedAssessmentsNewRoute,
  AuthenticatedCapabilityAssessmentIdRoute:
    AuthenticatedCapabilityAssessmentIdRoute,
  AuthenticatedFieldFieldIdRoute: AuthenticatedFieldFieldIdRoute,
  AuthenticatedAssessmentsIndexRoute: AuthenticatedAssessmentsIndexRoute,
  AuthenticatedCapabilityIndexRoute: AuthenticatedCapabilityIndexRoute,
  AuthenticatedFieldIndexRoute: AuthenticatedFieldIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
