/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdministrationRouteImport } from './routes/_authenticated/administration'
import { Route as AuthenticatedAskIroniqRouteImport } from './routes/_authenticated/ask-ironiq'
import { Route as AuthenticatedAssessmentRouteImport } from './routes/_authenticated/assessment'
import { Route as AuthenticatedCadRouteImport } from './routes/_authenticated/cad'
import { Route as AuthenticatedCncRouteImport } from './routes/_authenticated/cnc'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEstimatesRouteImport } from './routes/_authenticated/estimates'
import { Route as AuthenticatedExecutiveRollupRouteImport } from './routes/_authenticated/executive-rollup'
import { Route as AuthenticatedFacilitiesRouteImport } from './routes/_authenticated/facilities'
import { Route as AuthenticatedFindingsRouteImport } from './routes/_authenticated/findings'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedIntakeRouteImport } from './routes/_authenticated/intake'
import { Route as AuthenticatedOrganizationsRouteImport } from './routes/_authenticated/organizations'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedAssessmentsIndexRouteImport } from './routes/_authenticated/assessments/index'
import { Route as AuthenticatedAssessmentsAssessmentIdRouteImport } from './routes/_authenticated/assessments/$assessmentId'
import { Route as AuthenticatedAssessmentsNewRouteImport } from './routes/_authenticated/assessments/new'
import { Route as AuthenticatedBusinessDevelopmentIndexRouteImport } from './routes/_authenticated/business-development/index'
import { Route as AuthenticatedBusinessDevelopmentProspectIdRouteImport } from './routes/_authenticated/business-development/$prospectId'
import { Route as AuthenticatedCapabilityIndexRouteImport } from './routes/_authenticated/capability/index'
import { Route as AuthenticatedCapabilityAssessmentIdRouteImport } from './routes/_authenticated/capability/$assessmentId'
import { Route as AuthenticatedFieldIndexRouteImport } from './routes/_authenticated/field/index'
import { Route as AuthenticatedFieldFieldIdRouteImport } from './routes/_authenticated/field/$fieldId'
import { Route as AuthenticatedMachinesIndexRouteImport } from './routes/_authenticated/machines/index'
import { Route as AuthenticatedMachinesMachineIdRouteImport } from './routes/_authenticated/machines/$machineId'
import { Route as AuthenticatedMachinesProgramMapRouteImport } from './routes/_authenticated/machines/program-map'
import { Route as AuthenticatedProductionIndexRouteImport } from './routes/_authenticated/production.index'
import { Route as AuthenticatedProductionLibrariesRouteImport } from './routes/_authenticated/production.libraries'
import { Route as AuthenticatedProductionNewRouteImport } from './routes/_authenticated/production.new'
import { Route as AuthenticatedProductionJobsJobIdRouteImport } from './routes/_authenticated/production.jobs.$jobId'
import { Route as ApiIroniqV1MachineEventsRouteImport } from './routes/api/ironiq/v1/machine-events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdministrationRoute =
  AuthenticatedAdministrationRouteImport.update({
    id: '/administration',
    path: '/administration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAskIroniqRoute = AuthenticatedAskIroniqRouteImport.update({
  id: '/ask-ironiq',
  path: '/ask-ironiq',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessmentRoute = AuthenticatedAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCadRoute = AuthenticatedCadRouteImport.update({
  id: '/cad',
  path: '/cad',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCncRoute = AuthenticatedCncRouteImport.update({
  id: '/cnc',
  path: '/cnc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstimatesRoute = AuthenticatedEstimatesRouteImport.update({
  id: '/estimates',
  path: '/estimates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExecutiveRollupRoute =
  AuthenticatedExecutiveRollupRouteImport.update({
    id: '/executive-rollup',
    path: '/executive-rollup',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFacilitiesRoute = AuthenticatedFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFindingsRoute = AuthenticatedFindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntakeRoute = AuthenticatedIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrganizationsRoute =
  AuthenticatedOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessmentsIndexRoute =
  AuthenticatedAssessmentsIndexRouteImport.update({
    id: '/assessments/',
    path: '/assessments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentsAssessmentIdRoute =
  AuthenticatedAssessmentsAssessmentIdRouteImport.update({
    id: '/assessments/$assessmentId',
    path: '/assessments/$assessmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentsNewRoute =
  AuthenticatedAssessmentsNewRouteImport.update({
    id: '/assessments/new',
    path: '/assessments/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessDevelopmentIndexRoute =
  AuthenticatedBusinessDevelopmentIndexRouteImport.update({
    id: '/business-development/',
    path: '/business-development/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessDevelopmentProspectIdRoute =
  AuthenticatedBusinessDevelopmentProspectIdRouteImport.update({
    id: '/business-development/$prospectId',
    path: '/business-development/$prospectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCapabilityIndexRoute =
  AuthenticatedCapabilityIndexRouteImport.update({
    id: '/capability/',
    path: '/capability/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCapabilityAssessmentIdRoute =
  AuthenticatedCapabilityAssessmentIdRouteImport.update({
    id: '/capability/$assessmentId',
    path: '/capability/$assessmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFieldIndexRoute = AuthenticatedFieldIndexRouteImport.update({
  id: '/field/',
  path: '/field/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFieldFieldIdRoute =
  AuthenticatedFieldFieldIdRouteImport.update({
    id: '/field/$fieldId',
    path: '/field/$fieldId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMachinesIndexRoute =
  AuthenticatedMachinesIndexRouteImport.update({
    id: '/machines/',
    path: '/machines/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMachinesMachineIdRoute =
  AuthenticatedMachinesMachineIdRouteImport.update({
    id: '/machines/$machineId',
    path: '/machines/$machineId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMachinesProgramMapRoute =
  AuthenticatedMachinesProgramMapRouteImport.update({
    id: '/machines/program-map',
    path: '/machines/program-map',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionIndexRoute =
  AuthenticatedProductionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const AuthenticatedProductionLibrariesRoute =
  AuthenticatedProductionLibrariesRouteImport.update({
    id: '/libraries',
    path: '/libraries',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const AuthenticatedProductionNewRoute =
  AuthenticatedProductionNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const AuthenticatedProductionJobsJobIdRoute =
  AuthenticatedProductionJobsJobIdRouteImport.update({
    id: '/jobs/$jobId',
    path: '/jobs/$jobId',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const ApiIroniqV1MachineEventsRoute =
  ApiIroniqV1MachineEventsRouteImport.update({
    id: '/api/ironiq/v1/machine-events',
    path: '/api/ironiq/v1/machine-events',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/administration': typeof AuthenticatedAdministrationRoute
  '/ask-ironiq': typeof AuthenticatedAskIroniqRoute
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/cad': typeof AuthenticatedCadRoute
  '/cnc': typeof AuthenticatedCncRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estimates': typeof AuthenticatedEstimatesRoute
  '/executive-rollup': typeof AuthenticatedExecutiveRollupRoute
  '/facilities': typeof AuthenticatedFacilitiesRoute
  '/findings': typeof AuthenticatedFindingsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/organizations': typeof AuthenticatedOrganizationsRoute
  '/production': typeof AuthenticatedProductionRouteWithChildren
  '/projects': typeof AuthenticatedProjectsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/assessments/$assessmentId': typeof AuthenticatedAssessmentsAssessmentIdRoute
  '/assessments/new': typeof AuthenticatedAssessmentsNewRoute
  '/business-development/$prospectId': typeof AuthenticatedBusinessDevelopmentProspectIdRoute
  '/capability/$assessmentId': typeof AuthenticatedCapabilityAssessmentIdRoute
  '/field/$fieldId': typeof AuthenticatedFieldFieldIdRoute
  '/machines/$machineId': typeof AuthenticatedMachinesMachineIdRoute
  '/machines/program-map': typeof AuthenticatedMachinesProgramMapRoute
  '/production/libraries': typeof AuthenticatedProductionLibrariesRoute
  '/production/new': typeof AuthenticatedProductionNewRoute
  '/assessments/': typeof AuthenticatedAssessmentsIndexRoute
  '/business-development/': typeof AuthenticatedBusinessDevelopmentIndexRoute
  '/capability/': typeof AuthenticatedCapabilityIndexRoute
  '/field/': typeof AuthenticatedFieldIndexRoute
  '/machines/': typeof AuthenticatedMachinesIndexRoute
  '/production/': typeof AuthenticatedProductionIndexRoute
  '/production/jobs/$jobId': typeof AuthenticatedProductionJobsJobIdRoute
  '/api/ironiq/v1/machine-events': typeof ApiIroniqV1MachineEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/administration': typeof AuthenticatedAdministrationRoute
  '/ask-ironiq': typeof AuthenticatedAskIroniqRoute
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/cad': typeof AuthenticatedCadRoute
  '/cnc': typeof AuthenticatedCncRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estimates': typeof AuthenticatedEstimatesRoute
  '/executive-rollup': typeof AuthenticatedExecutiveRollupRoute
  '/facilities': typeof AuthenticatedFacilitiesRoute
  '/findings': typeof AuthenticatedFindingsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/organizations': typeof AuthenticatedOrganizationsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/assessments/$assessmentId': typeof AuthenticatedAssessmentsAssessmentIdRoute
  '/assessments/new': typeof AuthenticatedAssessmentsNewRoute
  '/business-development/$prospectId': typeof AuthenticatedBusinessDevelopmentProspectIdRoute
  '/capability/$assessmentId': typeof AuthenticatedCapabilityAssessmentIdRoute
  '/field/$fieldId': typeof AuthenticatedFieldFieldIdRoute
  '/machines/$machineId': typeof AuthenticatedMachinesMachineIdRoute
  '/machines/program-map': typeof AuthenticatedMachinesProgramMapRoute
  '/production/libraries': typeof AuthenticatedProductionLibrariesRoute
  '/production/new': typeof AuthenticatedProductionNewRoute
  '/assessments': typeof AuthenticatedAssessmentsIndexRoute
  '/business-development': typeof AuthenticatedBusinessDevelopmentIndexRoute
  '/capability': typeof AuthenticatedCapabilityIndexRoute
  '/field': typeof AuthenticatedFieldIndexRoute
  '/machines': typeof AuthenticatedMachinesIndexRoute
  '/production': typeof AuthenticatedProductionIndexRoute
  '/production/jobs/$jobId': typeof AuthenticatedProductionJobsJobIdRoute
  '/api/ironiq/v1/machine-events': typeof ApiIroniqV1MachineEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/administration': typeof AuthenticatedAdministrationRoute
  '/_authenticated/ask-ironiq': typeof AuthenticatedAskIroniqRoute
  '/_authenticated/assessment': typeof AuthenticatedAssessmentRoute
  '/_authenticated/cad': typeof AuthenticatedCadRoute
  '/_authenticated/cnc': typeof AuthenticatedCncRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/estimates': typeof AuthenticatedEstimatesRoute
  '/_authenticated/executive-rollup': typeof AuthenticatedExecutiveRollupRoute
  '/_authenticated/facilities': typeof AuthenticatedFacilitiesRoute
  '/_authenticated/findings': typeof AuthenticatedFindingsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/intake': typeof AuthenticatedIntakeRoute
  '/_authenticated/organizations': typeof AuthenticatedOrganizationsRoute
  '/_authenticated/production': typeof AuthenticatedProductionRouteWithChildren
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/assessments/$assessmentId': typeof AuthenticatedAssessmentsAssessmentIdRoute
  '/_authenticated/assessments/new': typeof AuthenticatedAssessmentsNewRoute
  '/_authenticated/business-development/$prospectId': typeof AuthenticatedBusinessDevelopmentProspectIdRoute
  '/_authenticated/capability/$assessmentId': typeof AuthenticatedCapabilityAssessmentIdRoute
  '/_authenticated/field/$fieldId': typeof AuthenticatedFieldFieldIdRoute
  '/_authenticated/machines/$machineId': typeof AuthenticatedMachinesMachineIdRoute
  '/_authenticated/machines/program-map': typeof AuthenticatedMachinesProgramMapRoute
  '/_authenticated/production/libraries': typeof AuthenticatedProductionLibrariesRoute
  '/_authenticated/production/new': typeof AuthenticatedProductionNewRoute
  '/_authenticated/assessments/': typeof AuthenticatedAssessmentsIndexRoute
  '/_authenticated/business-development/': typeof AuthenticatedBusinessDevelopmentIndexRoute
  '/_authenticated/capability/': typeof AuthenticatedCapabilityIndexRoute
  '/_authenticated/field/': typeof AuthenticatedFieldIndexRoute
  '/_authenticated/machines/': typeof AuthenticatedMachinesIndexRoute
  '/_authenticated/production/': typeof AuthenticatedProductionIndexRoute
  '/_authenticated/production/jobs/$jobId': typeof AuthenticatedProductionJobsJobIdRoute
  '/api/ironiq/v1/machine-events': typeof ApiIroniqV1MachineEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/administration'
    | '/ask-ironiq'
    | '/assessment'
    | '/cad'
    | '/cnc'
    | '/dashboard'
    | '/estimates'
    | '/executive-rollup'
    | '/facilities'
    | '/findings'
    | '/home'
    | '/intake'
    | '/organizations'
    | '/production'
    | '/projects'
    | '/reports'
    | '/templates'
    | '/assessments/$assessmentId'
    | '/assessments/new'
    | '/business-development/$prospectId'
    | '/capability/$assessmentId'
    | '/field/$fieldId'
    | '/machines/$machineId'
    | '/machines/program-map'
    | '/production/libraries'
    | '/production/new'
    | '/assessments/'
    | '/business-development/'
    | '/capability/'
    | '/field/'
    | '/machines/'
    | '/production/'
    | '/production/jobs/$jobId'
    | '/api/ironiq/v1/machine-events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/administration'
    | '/ask-ironiq'
    | '/assessment'
    | '/cad'
    | '/cnc'
    | '/dashboard'
    | '/estimates'
    | '/executive-rollup'
    | '/facilities'
    | '/findings'
    | '/home'
    | '/intake'
    | '/organizations'
    | '/projects'
    | '/reports'
    | '/templates'
    | '/assessments/$assessmentId'
    | '/assessments/new'
    | '/business-development/$prospectId'
    | '/capability/$assessmentId'
    | '/field/$fieldId'
    | '/machines/$machineId'
    | '/machines/program-map'
    | '/production/libraries'
    | '/production/new'
    | '/assessments'
    | '/business-development'
    | '/capability'
    | '/field'
    | '/machines'
    | '/production'
    | '/production/jobs/$jobId'
    | '/api/ironiq/v1/machine-events'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/administration'
    | '/_authenticated/ask-ironiq'
    | '/_authenticated/assessment'
    | '/_authenticated/cad'
    | '/_authenticated/cnc'
    | '/_authenticated/dashboard'
    | '/_authenticated/estimates'
    | '/_authenticated/executive-rollup'
    | '/_authenticated/facilities'
    | '/_authenticated/findings'
    | '/_authenticated/home'
    | '/_authenticated/intake'
    | '/_authenticated/organizations'
    | '/_authenticated/production'
    | '/_authenticated/projects'
    | '/_authenticated/reports'
    | '/_authenticated/templates'
    | '/_authenticated/assessments/$assessmentId'
    | '/_authenticated/assessments/new'
    | '/_authenticated/business-development/$prospectId'
    | '/_authenticated/capability/$assessmentId'
    | '/_authenticated/field/$fieldId'
    | '/_authenticated/machines/$machineId'
    | '/_authenticated/machines/program-map'
    | '/_authenticated/production/libraries'
    | '/_authenticated/production/new'
    | '/_authenticated/assessments/'
    | '/_authenticated/business-development/'
    | '/_authenticated/capability/'
    | '/_authenticated/field/'
    | '/_authenticated/machines/'
    | '/_authenticated/production/'
    | '/_authenticated/production/jobs/$jobId'
    | '/api/ironiq/v1/machine-events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiIroniqV1MachineEventsRoute: typeof ApiIroniqV1MachineEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/administration': {
      id: '/_authenticated/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AuthenticatedAdministrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ask-ironiq': {
      id: '/_authenticated/ask-ironiq'
      path: '/ask-ironiq'
      fullPath: '/ask-ironiq'
      preLoaderRoute: typeof AuthenticatedAskIroniqRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment': {
      id: '/_authenticated/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AuthenticatedAssessmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cad': {
      id: '/_authenticated/cad'
      path: '/cad'
      fullPath: '/cad'
      preLoaderRoute: typeof AuthenticatedCadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cnc': {
      id: '/_authenticated/cnc'
      path: '/cnc'
      fullPath: '/cnc'
      preLoaderRoute: typeof AuthenticatedCncRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estimates': {
      id: '/_authenticated/estimates'
      path: '/estimates'
      fullPath: '/estimates'
      preLoaderRoute: typeof AuthenticatedEstimatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/executive-rollup': {
      id: '/_authenticated/executive-rollup'
      path: '/executive-rollup'
      fullPath: '/executive-rollup'
      preLoaderRoute: typeof AuthenticatedExecutiveRollupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facilities': {
      id: '/_authenticated/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof AuthenticatedFacilitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/findings': {
      id: '/_authenticated/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof AuthenticatedFindingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intake': {
      id: '/_authenticated/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof AuthenticatedIntakeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations': {
      id: '/_authenticated/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthenticatedOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/': {
      id: '/_authenticated/assessments/'
      path: '/assessments'
      fullPath: '/assessments/'
      preLoaderRoute: typeof AuthenticatedAssessmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/$assessmentId': {
      id: '/_authenticated/assessments/$assessmentId'
      path: '/assessments/$assessmentId'
      fullPath: '/assessments/$assessmentId'
      preLoaderRoute: typeof AuthenticatedAssessmentsAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/new': {
      id: '/_authenticated/assessments/new'
      path: '/assessments/new'
      fullPath: '/assessments/new'
      preLoaderRoute: typeof AuthenticatedAssessmentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business-development/': {
      id: '/_authenticated/business-development/'
      path: '/business-development'
      fullPath: '/business-development/'
      preLoaderRoute: typeof AuthenticatedBusinessDevelopmentIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business-development/$prospectId': {
      id: '/_authenticated/business-development/$prospectId'
      path: '/business-development/$prospectId'
      fullPath: '/business-development/$prospectId'
      preLoaderRoute: typeof AuthenticatedBusinessDevelopmentProspectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/capability/': {
      id: '/_authenticated/capability/'
      path: '/capability'
      fullPath: '/capability/'
      preLoaderRoute: typeof AuthenticatedCapabilityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/capability/$assessmentId': {
      id: '/_authenticated/capability/$assessmentId'
      path: '/capability/$assessmentId'
      fullPath: '/capability/$assessmentId'
      preLoaderRoute: typeof AuthenticatedCapabilityAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/field/': {
      id: '/_authenticated/field/'
      path: '/field'
      fullPath: '/field/'
      preLoaderRoute: typeof AuthenticatedFieldIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/field/$fieldId': {
      id: '/_authenticated/field/$fieldId'
      path: '/field/$fieldId'
      fullPath: '/field/$fieldId'
      preLoaderRoute: typeof AuthenticatedFieldFieldIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/machines/': {
      id: '/_authenticated/machines/'
      path: '/machines'
      fullPath: '/machines/'
      preLoaderRoute: typeof AuthenticatedMachinesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/machines/$machineId': {
      id: '/_authenticated/machines/$machineId'
      path: '/machines/$machineId'
      fullPath: '/machines/$machineId'
      preLoaderRoute: typeof AuthenticatedMachinesMachineIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/machines/program-map': {
      id: '/_authenticated/machines/program-map'
      path: '/machines/program-map'
      fullPath: '/machines/program-map'
      preLoaderRoute: typeof AuthenticatedMachinesProgramMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production/': {
      id: '/_authenticated/production/'
      path: '/'
      fullPath: '/production/'
      preLoaderRoute: typeof AuthenticatedProductionIndexRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/_authenticated/production/libraries': {
      id: '/_authenticated/production/libraries'
      path: '/libraries'
      fullPath: '/production/libraries'
      preLoaderRoute: typeof AuthenticatedProductionLibrariesRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/_authenticated/production/new': {
      id: '/_authenticated/production/new'
      path: '/new'
      fullPath: '/production/new'
      preLoaderRoute: typeof AuthenticatedProductionNewRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/_authenticated/production/jobs/$jobId': {
      id: '/_authenticated/production/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/production/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedProductionJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/api/ironiq/v1/machine-events': {
      id: '/api/ironiq/v1/machine-events'
      path: '/api/ironiq/v1/machine-events'
      fullPath: '/api/ironiq/v1/machine-events'
      preLoaderRoute: typeof ApiIroniqV1MachineEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedProductionRouteChildren {
  AuthenticatedProductionLibrariesRoute: typeof AuthenticatedProductionLibrariesRoute
  AuthenticatedProductionNewRoute: typeof AuthenticatedProductionNewRoute
  AuthenticatedProductionIndexRoute: typeof AuthenticatedProductionIndexRoute
  AuthenticatedProductionJobsJobIdRoute: typeof AuthenticatedProductionJobsJobIdRoute
}

const AuthenticatedProductionRouteChildren: AuthenticatedProductionRouteChildren =
  {
    AuthenticatedProductionLibrariesRoute:
      AuthenticatedProductionLibrariesRoute,
    AuthenticatedProductionNewRoute: AuthenticatedProductionNewRoute,
    AuthenticatedProductionIndexRoute: AuthenticatedProductionIndexRoute,
    AuthenticatedProductionJobsJobIdRoute:
      AuthenticatedProductionJobsJobIdRoute,
  }

const AuthenticatedProductionRouteWithChildren =
  AuthenticatedProductionRoute._addFileChildren(
    AuthenticatedProductionRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdministrationRoute: typeof AuthenticatedAdministrationRoute
  AuthenticatedAskIroniqRoute: typeof AuthenticatedAskIroniqRoute
  AuthenticatedAssessmentRoute: typeof AuthenticatedAssessmentRoute
  AuthenticatedCadRoute: typeof AuthenticatedCadRoute
  AuthenticatedCncRoute: typeof AuthenticatedCncRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEstimatesRoute: typeof AuthenticatedEstimatesRoute
  AuthenticatedExecutiveRollupRoute: typeof AuthenticatedExecutiveRollupRoute
  AuthenticatedFacilitiesRoute: typeof AuthenticatedFacilitiesRoute
  AuthenticatedFindingsRoute: typeof AuthenticatedFindingsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedIntakeRoute: typeof AuthenticatedIntakeRoute
  AuthenticatedOrganizationsRoute: typeof AuthenticatedOrganizationsRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRouteWithChildren
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedAssessmentsAssessmentIdRoute: typeof AuthenticatedAssessmentsAssessmentIdRoute
  AuthenticatedAssessmentsNewRoute: typeof AuthenticatedAssessmentsNewRoute
  AuthenticatedBusinessDevelopmentProspectIdRoute: typeof AuthenticatedBusinessDevelopmentProspectIdRoute
  AuthenticatedCapabilityAssessmentIdRoute: typeof AuthenticatedCapabilityAssessmentIdRoute
  AuthenticatedFieldFieldIdRoute: typeof AuthenticatedFieldFieldIdRoute
  AuthenticatedMachinesMachineIdRoute: typeof AuthenticatedMachinesMachineIdRoute
  AuthenticatedMachinesProgramMapRoute: typeof AuthenticatedMachinesProgramMapRoute
  AuthenticatedAssessmentsIndexRoute: typeof AuthenticatedAssessmentsIndexRoute
  AuthenticatedBusinessDevelopmentIndexRoute: typeof AuthenticatedBusinessDevelopmentIndexRoute
  AuthenticatedCapabilityIndexRoute: typeof AuthenticatedCapabilityIndexRoute
  AuthenticatedFieldIndexRoute: typeof AuthenticatedFieldIndexRoute
  AuthenticatedMachinesIndexRoute: typeof AuthenticatedMachinesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdministrationRoute: AuthenticatedAdministrationRoute,
  AuthenticatedAskIroniqRoute: AuthenticatedAskIroniqRoute,
  AuthenticatedAssessmentRoute: AuthenticatedAssessmentRoute,
  AuthenticatedCadRoute: AuthenticatedCadRoute,
  AuthenticatedCncRoute: AuthenticatedCncRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEstimatesRoute: AuthenticatedEstimatesRoute,
  AuthenticatedExecutiveRollupRoute: AuthenticatedExecutiveRollupRoute,
  AuthenticatedFacilitiesRoute: AuthenticatedFacilitiesRoute,
  AuthenticatedFindingsRoute: AuthenticatedFindingsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedIntakeRoute: AuthenticatedIntakeRoute,
  AuthenticatedOrganizationsRoute: AuthenticatedOrganizationsRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRouteWithChildren,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedAssessmentsAssessmentIdRoute:
    AuthenticatedAssessmentsAssessmentIdRoute,
  AuthenticatedAssessmentsNewRoute: AuthenticatedAssessmentsNewRoute,
  AuthenticatedBusinessDevelopmentProspectIdRoute:
    AuthenticatedBusinessDevelopmentProspectIdRoute,
  AuthenticatedCapabilityAssessmentIdRoute:
    AuthenticatedCapabilityAssessmentIdRoute,
  AuthenticatedFieldFieldIdRoute: AuthenticatedFieldFieldIdRoute,
  AuthenticatedMachinesMachineIdRoute: AuthenticatedMachinesMachineIdRoute,
  AuthenticatedMachinesProgramMapRoute: AuthenticatedMachinesProgramMapRoute,
  AuthenticatedAssessmentsIndexRoute: AuthenticatedAssessmentsIndexRoute,
  AuthenticatedBusinessDevelopmentIndexRoute:
    AuthenticatedBusinessDevelopmentIndexRoute,
  AuthenticatedCapabilityIndexRoute: AuthenticatedCapabilityIndexRoute,
  AuthenticatedFieldIndexRoute: AuthenticatedFieldIndexRoute,
  AuthenticatedMachinesIndexRoute: AuthenticatedMachinesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiIroniqV1MachineEventsRoute: ApiIroniqV1MachineEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
